#acu user configurations
configurations:

  # load device configuration determined by tags (e.g. rock-5b)
  #device_config: generic-aarch64

  # do not update (overwrite) this configuration file during an update
  # if you edited this configuration file, uncomment this to prevent ACU overwriting it during an update
  #no_config_update: 1

  # do not confirm when installing a package using pacman -S / -U or makepkg -si
  #no_confirm: 1

  # do not print warning ($YELLOW) messages
  #no_warning: 1

  # do not clear terminal outputs
  #no_clear: 1

  # do not print warning ($YELLOW) messages
  #debug_log: 1

  # auto update acu when launch without asking
  #auto_update: 1

  # archive repo url for downgrading packages
  # Arch Linux ARM Archive repo
  alaa_url: https://alaa.ad24.cz

  # directory for storing source files
  source_repo_dir: .acu/sources

  # Repositories List
  # repositories_file - file (or url) to load repositories list
  # repositories_url - Sync local file from url when fetching updates (optional)
  repositories_file: .acu/config/repo.yaml
  #repositories_url: https://raw.githubusercontent.com/kwankiu/acu/dev/example/repo.yaml

  # Tags List
  # tags_file - file to load tags list
  # tags_url - Sync local file from url when fetching updates (optional)
  tags_file: .acu/config/tags.yaml
  tags_url: https://raw.githubusercontent.com/kwankiu/acu/dev/example/tags.yaml

  # Kernel List
  # kernel_file - file to load kernel list
  # kernel_url - Sync local file from url when fetching updates (optional)
  kernel_file: .acu/config/kernel.yaml
  kernel_url: https://raw.githubusercontent.com/kwankiu/acu/dev/example/kernel.yaml

  # Bootloader List
  # bootloader_file - file to load bootloader list
  # bootloader_url - Sync local file from url when fetching updates (optional)
  bootloader_file: .acu/config/bootloader.yaml
  bootloader_url: https://raw.githubusercontent.com/kwankiu/acu/dev/example/bootloader.yaml

  # Apps List
  # apps_file - file to load apps list
  # apps_url - Sync local file from url when fetching updates (optional)
  apps_file: .acu/config/apps.yaml
  apps_url: https://raw.githubusercontent.com/kwankiu/acu/dev/example/apps.yaml
